name: Build
on:
  workflow_dispatch:
jobs:
  build-mac:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Install and Build
      run:
        npm install && npm run build
    - name: Upload File
      uses: actions/upload-artifact@v2
      with:
        name: mac
        path: dist/*dmg